# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-28 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.CharField(max_length=200)),
                ('top_level_function', models.CharField(blank=True, max_length=200)),
                ('version', models.IntegerField()),
                ('cpu_profile', models.FileField(upload_to=profiles.models.get_profile_storage_directory)),
                ('memory_profile', models.FileField(upload_to=profiles.models.get_profile_storage_directory)),
                ('addr_name_map', models.FileField(upload_to=profiles.models.get_profile_storage_directory)),
                ('max_memory_use', models.BigIntegerField(blank=True, null=True)),
                ('time_spent', models.BigIntegerField(blank=True, null=True)),
                ('profile_resolution', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
