# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import vmmemory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryProfile',
            fields=[
                ('checksum', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('memory_profile', models.FileField(upload_to=vmmemory.models.get_profile_storage_directory)),
                ('addr_name_map', models.FileField(upload_to=vmmemory.models.get_profile_storage_directory)),
                ('version', models.IntegerField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('project', models.CharField(max_length=200)),
                ('top_level_function', models.CharField(blank=True, max_length=200)),
                ('max_memory_use', models.BigIntegerField(blank=True, null=True)),
                ('time_spent', models.BigIntegerField(blank=True, null=True)),
                ('profile_resolution', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
