# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import vmmemory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vmprofile', '0005_log_cpu_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_profile', models.FileField(upload_to=vmmemory.models.get_profile_storage_directory)),
                ('addr_name_map', models.FileField(upload_to=vmmemory.models.get_profile_storage_directory)),
                ('version', models.IntegerField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('project', models.CharField(max_length=200)),
                ('top_level_function', models.CharField(blank=True, max_length=200)),
                ('max_memory_use', models.BigIntegerField(blank=True, null=True)),
                ('time_spent', models.BigIntegerField(blank=True, null=True)),
                ('profile_resolution', models.BigIntegerField(blank=True, null=True)),
                ('upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_profile', to='vmprofile.Log')),
            ],
        ),
    ]
