# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binaryjitlog',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jitlog', to='vmprofile.Log'),
        ),
    ]
