# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import vmlog.models


class Migration(migrations.Migration):

    dependencies = [
        ('vmlog', '0002_auto_20160915_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binaryjitlog',
            name='user',
        ),
        migrations.AlterField(
            model_name='binaryjitlog',
            name='checksum',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='binaryjitlog',
            name='file',
            field=models.FileField(upload_to=vmlog.models.get_profile_storage_directory),
        ),
    ]
