# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmlog', '0003_auto_20160915_1542'),
        ('vmprofile', '0007_auto_20160915_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binaryjitlog',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jitlog', to='vmprofile.RuntimeData'),
        ),
    ]
