# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import vmprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('vmprofile', '0004_auto_20150921_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='cpu_profile',
            field=models.FileField(default=None, upload_to=vmprofile.models.get_profile_storage_directory),
            preserve_default=False,
        ),
    ]
