# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('vmprofile', '0004_auto_20150921_1116'),
        ('vmlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Log', 'CPUProfile')
    ]
