# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmprofile', '0007_auto_20160915_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuprofile',
            name='arch',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='cpuprofile',
            name='os',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='runtimedata',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='runtimedata',
            name='stop_time',
            field=models.DateTimeField(null=True),
        ),
    ]
