# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2022-02-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmprofile', '0009_auto_20161222_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
