# Generated by Django 3.2.12 on 2022-02-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmprofile', '0009_auto_20161222_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtimedata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
